let From_server = [
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
     {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
     {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
     {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
     {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
     {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },{
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    }, {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
    {
        id:1,
        code:"10.10.10.10.10",
        business:"Облачные услуги",
        lob:"10",
        liveservice:"Услуги DF Cloud",
        srvlive:"10",
        service:"DF Cloud On Demand",
        srv:"10",
        elmservice:"Вычислительные расчеты",
        srlel:"10",
        tarif:"low 150",
        tarrif:"11",
        eltarif:"ВМ vCPU",
        edtarif:"1 vRAM GB*час",
        typetarif:"usage based",
        recalculation:"да"
    },
   
 
    
    
]


export {From_server}